services:
  db:
    image: mysql
    restart: always
    #ports:
    #- 3306:3306
    environment:
      #MYSQL_DATABASE: Prueba
      MYSQL_ROOT_PASSWORD: pass
      #MYSQL_USER: AleMorales09
      #MYSQL_PASSWORD: MAM2025
    networks:
      - network1

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      #MYSQL_ROOT_PASSWORD: MAM2025
    networks:
      - network1
    depends_on:
      - db

networks:
  network1:
    driver: bridge